version: '3.3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - webnet

  swi-prolog:
    build: ./prolog
    networks:
      - webnet

  api:
    build: ./api
    networks:
    - webnet
    depends_on:
      - swi-prolog

networks:
  webnet:
    driver: bridge
