version: '3.3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webnet

  api:
    build: ./api
    networks:
      - webnet
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true

  sudoku-cli:
    build: ./prolog
    networks:
      - webnet
      
networks:
  webnet:
    driver: bridge
