version: '3.3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - webnet

  swi-prolog:
    build: ./prolog
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
